Task 2. Review 1
AlexanderRozhnev/cpp-peer-review pull request #2
Opened 2023-11-09 13:33 UTC by AlexanderRozhnev

Task 2 for review. Try 1.

2023-11-10 12:35 UTC, Peretz489 requested changes
Предлагаю некоторые изменения. Всё в общем прилично, но кое-что в глаза бросилось.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +            return ((domain_ + '.') == domain.domain_.substr(0, size + 1));
Вот как -то непонятно тут выглядит добавление точки. То есть понятно в случае если сам писал уже, но при первом просмотре вызывает вопросы.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +    string Get() const {
А зачем этот метод?  GetRaw покрывает все потребности операторов. Только честно говоря Raw тут именно прямое написание, а не обратное :)

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +        for (InputIt it = begin; it != end; ++it) {
Может, проще это было бы через стандартный конструктор сделать в списке инициализации? Какие преимущества у подхода с циклом?

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +                return lexicographical_compare(left.GetRaw().begin(), left.GetRaw().end(),
А вот тут lexicographical_compare по-моему лишнее. Сортировка строк она и есть сортировка строк.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +            [](const Domain& left, const Domain& right){
Можно без лямбды, поскольку реализован оператор ==

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +        domains_.erase(last, domains_.end());
Это не замечание, а просто рассуждение. Eraise прибивает дубликаты, capacity вектора остаётся постоянным, соответственно зарезервировано пустое место, которое не будет использоваться никогда. Сам тоже на эти грабли наступил, оказывается есть функция shrink_to_fit(), уменьшающая capacity. Но она вызывает реаллокацию, т.е. потенциально это источник исключений. Тут надо взвесить, что лучше: рискнуть провести реаллокацию или потратить впустую кус памяти.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +            return ((domain == *upper) || (*upper).IsSubdomain(domain));
Можно упростить, проверка на равенство не обязательна, результат определяется как domain.IsSubdomain(*std::prev(upper))

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +    vector<Domain> domains_;
Не очень удачное имя, не отражает сути.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +void Test() {
Тесты огонь.

2023-11-10 12:35 UTC, Peretz489 commented on main.cpp
> +void TestDomainChekerClass() {
Всё же Checker :)

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +            return ((domain_ + '.') == domain.domain_.substr(0, size + 1));
А какие она вызывает вопросы?
Точка "." тут нужна для корректного сравнения и проверки входения в ПОДдомен. Потому что, просто обрезать проверяемое имя по длине некорректно.
Допустим, мы проверяем является ли (this->domain_ = "maps.me") поддоменом "any.maps.me".
Отрезали до "maps.me" и сравнили - = true.
А если на входе "amaps.me", то результат сказал бы тоже, что "maps.me" поддоменн. Но это не так.
Поэтому, для корректности сравнения и нужно добавление точки.
В 1-м случае сравниваем ".maps.me" с ".maps.me" (=true), а во втором ".maps.me" с "amaps.me" (=false).
И есть еще один момент: Если сравниваем "maps.me" с "maps.me", то, строго говоря, сравнваемое не является ПОДдоменом второго. Поэтому, в таком случае я считаю корректным результатом false.

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +    string Get() const {
Этот метод быд добавлен исключительно для тестирования класса. Чтобы возвращать имена в нормальном виде, а не в реверсивном. Допустим, при создании теста в ручном режиме, пришлось бы каждый раз ручками переворачивать тестовые имена. А для автоматизированных тестов дописать функцию отзеркаливания перед проверкой. Т.е., в любом случае, чтобы избежать ручной работы, нужно что-то написать.. Вот, и встроил прямо в класс, чтобы не думалось при составлении юнит-тестов.
Raw означает "исходный", "необработанный".

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +                return lexicographical_compare(left.GetRaw().begin(), left.GetRaw().end(),
Да. В документации по string так и написано, что оператор < основан на алгоритме эквивалентном lexicographical_compare(). Поэтому, результат идентичен.
Но вот, что интересно: в документации string написано, что оператор < убран, начиная с C++20
https://en.cppreference.com/w/cpp/string/basic_string

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +            [](const Domain& left, const Domain& right){
Тут в лямбде проверка на поддомен. Оператор== не выполняет функцию проверки на поддомен. Он занимается только их сравнением. Поэтому, без лямбды не будет происходить сворачивание поддоменов.

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +        domains_.erase(last, domains_.end());
Да. Полностью согласен. Тут надо выбирать что экономим память или скорость.

2023-11-10 17:32 UTC, AlexanderRozhnev commented on main.cpp
> +            return ((domain == *upper) || (*upper).IsSubdomain(domain));
У нас разночтение из-за реализации IsSubDomain.
Я подошел к проверке IsSubDomain строго. Поддоментом является только то действительно является составной частью домена. Как описал выше в комментарий в методе IsSubDomain(), сравнение "maps.me" с "maps.me" даёт false.
Т.е. у меня метод IsSubDomain отвечает строго на вопрос "является ли поддоменом?", а оператор= - "равны ли между собой наименования?" Поэтому здесь необходима проверка обеих условий.

2023-11-10 20:55 UTC, Peretz489 commented on main.cpp
> +    string Get() const {
Так может этот метод оформить как отдельную функцию и в тесты засунуть?  На худой конец есть reverse(str.begin(), str.end()); ?

2023-11-10 20:55 UTC, Peretz489 commented on main.cpp
> +            return ((domain == *upper) || (*upper).IsSubdomain(domain));
А хорошо ли это? Получается двойная проверка, сначала на равенство посимвольно, потом на вхождение подстроки в строку посимвольно. А если принять, что домен является собственным поддоменом (звучит диковато, конечно), можно обойтись одной проверкой. Выигрыш будет значительный, строки сравнивать это занятие такое себе. А если lexicographical распараллелить так вообще... Если время будет, можно погонять тест и посмотреть, насколько это будет выгоднее. Опять же, при сортировке не нужна будет лямбда и в unique всё будет проще.

2023-11-10 21:22 UTC, AlexanderRozhnev commented on main.cpp
> +    string Get() const {
Поддерживаю. В финальном коде артефакты не нужны. Нужно выносить тестовое в тесты.

2023-11-12 07:41 UTC, Peretz489 requested changes
Лишний метод из класса удаляем, остальное дело вкуса.

2023-11-13 15:35 UTC, AlexanderRozhnev commented on main.cpp
> +            return ((domain == *upper) || (*upper).IsSubdomain(domain));
С одной стороны, это касается немногих случаев.
Но, если допустить, что IsSubdomain() будет называть равные домены поддоменами, дейстивительно, можно ускориться. Сделал именно такую версию.

2023-11-13 23:06 UTC, merged