Task 3. Review 1
AlexanderRozhnev/cpp-peer-review pull request #3
Opened 2023-11-13 23:05 UTC by AlexanderRozhnev

Task 3. Refactoring. Try 1.

2023-11-16 18:31 UTC, Peretz489 commented on CheckDateTimeValidity.cpp
> +enum class DateTimeErrorCode {
Хорошее решение если исключения не нужны.

2023-11-16 19:04 UTC, Peretz489 commented on LoadPerson.cpp
> +struct DBParamsBuilder {
Логика понятна, но делать builder для параметров совсем лишнее

2023-11-16 19:05 UTC, Peretz489 commented on LoadPerson.cpp
> +    operator DBParams() const {
Проще всё проверять в конструкторе объекта-базы, иначе ну очень сложно

2023-11-16 19:06 UTC, Peretz489 commented on LoadPerson.cpp
> +optional<DBHandler> GetDB(const DBParams& db_params) {
Вот этой функции, принимающей структуру, было бы достаточно.

2023-11-16 19:09 UTC, Peretz489 commented on LoadPerson.cpp
> +vector<Person> LoadPersons(int min_age, int max_age, string_view name_filter, const DBParams& db_params) {
А эта функция, если её делать индивидуальной, должна была бы принимать ссылку или указатель на базу и параметры поиска. Иначе набор входных значений не соответствует названию  и логике функции, не должна она принимать параметры для соединения с базой.

2023-11-16 19:09 UTC, Peretz489 requested changes
Две без вопросов, но интерфейс к базе лучше доработать

2023-11-22 13:17 UTC, AlexanderRozhnev commented on LoadPerson.cpp
> +vector<Person> LoadPersons(int min_age, int max_age, string_view name_filter, const DBParams& db_params) {
Согласен. Передача параметров в эту функцию неестественна. Исправляю сигнатуру этой функции на приём готового хендлера к БД. Вызывающая сторона берет на себя инициализацию хендлера с параметрами.
Пример вызова тоже чуть подправлю. См. следующий коммит.

2023-11-23 13:00 UTC, Peretz489 approved these changes
Я бы честно выкинул Builder как конструкцию, собирающую структуру инициализационных параметров, но поскольку он перешёл в разряд вспомогательных вещей, можно и так оставить.

2023-11-23 14:01 UTC, merged